<?php

namespace App\Http\Middleware;

use Closure;

class BlockBadBots
{
    public function handle($request, Closure $next)
    {
        $userAgent = $request->header('User-Agent');

        if ($this->isDisallowedBot($userAgent)) {
            abort(403, 'Access denied');
        }

        return $next($request);
    }

    protected function isDisallowedBot($userAgent)
    {
        // Define the list of disallowed bots.
        $disallowedBots = [
            'AhrefsBot/7.0',
            'PetalBot',
            '12soso',
            '192.comAgent',
            '1Noonbot',
            '1on1searchBot',
            '3D_SEARCH',
            '3DE_SEARCH2',
            '3GSE',
            '50.nu',
            'A1 Sitemap Generator',
            'A1 Website Download',
            'A6-Indexer',
            'AASP',
            'ABACHOBot',
            'Abonti',
            'abot',
            'AbotEmailSearch',
            'AboutUsBot',
            'AccMonitor Compliance Server',
            'accoona',
            'AChulkov.NET page walker',
            'Acme.Spider',
            'AcoonBot',
            'acquia-crawler',
            'ActiveTouristBot',
            'Ad Muncher',
            'AdamM Bot,',
            'adbeat_bot',
            'AdMedia bot',
            'adminshop.com',
            'Advanced Email Extractor',
            'AESOP_com_SpiderMan',
            'AESpider',
            'AF Knowledge Now Verity Spider',
            'aggregator:Vocus',
            'ah-ha.com crawler',
            'AhrefsBot',
            'AhrefsBot/5.0',
            'AIBOT',
            'aiHitBot',
            'aipbot',
            'AISIID',
            'AITCSRobot/1.1',
            'Akamai-SiteSnapshot',
            'AlexaWebSearchPlatform',
            'AlexfDownload',
            'Alexibot',
            'AlkalineBOT',
            'All Acronyms Bot',
            'Alpha Search Agent',
            'Amerla Search Bot',
            'Amfibibot',
            'AmPmPPC.com',
            'AMZNKAssocBot',
            'Anemone',
            'Anonymous/3G bot',
            'Anonymouse.org',
            'AnotherBot',
            'AnswerBot',
            'AnswerBus',
            'AnswerChase PROve',
            'AntBot',
            'antibot-',
            'AntiSantyWorm',
            'Antro.Net',
            'AONDE-Spider',
            'Apache-HttpClient',
            'Apache-HttpClient/4.0.1 (java 1.5)',
            'ApacheBench',
            'Aport',
            'appid: s~stremor-crawler-',
            'Aqua_Products',
            'AraBot',
            'Arachmo',
            'Arachnophilia',
            'archive.org_bot',
            'aria eQualizer',
            'arianna.libero.it',
            'Arikus_Spider',
            'Art-Online.com',
            'ArtavisBot',
            'Artera',
            'ASAHA Search Engine Turkey',
            'ASpider/0.09',
            'ASPSeek',
            'ASPseek',
            'asterias',
            'AstroFind',
            'athenusbot',
            'AtlocalBot',
            'Atomic_Email_Hunter',
            'attach',
            'attrakt',
            'Attributor.comBot',
            'attributor',
            'Attributor/Dejan-',
            'augurfind',
            'AURESYS',
            'AutoBaron crawler',
            'autoemailspider',
            'autowebdir',
            'AVSearch-',
            'axfeedsbot',
            'Axonize-bot',
            'Ayna',
            'b2w',
            'b2w/0.1',
            'BackDoorBot',
            'BackRub/.',
            'BackStreet Browser',
            'BackWeb',
            'Baiduspider',
            'BaiDuSpider',
            'BaiduSpider',
            'Baiduspider-video',
            'Baiduspider+',
            'Bandit',
            'BatchFTP',
            'baypup',
            'BDFetch',
            'BecomeBot',
            'BecomeJPBot',
            'BeetleBot',
            'Bender',
            'besserscheitern-crawl',
            'betaBot',
            'Big Brother',
            'Big Data',
            'Bigado.com',
            'BigCliqueBot',
            'BigCliqueBOT',
            'Bigfoot',
            'BIGLOTRON',
            'Bilbo',
            'BilgiBetaBot',
            'BilgiBot',
            'bintellibot',
            'bitlybot',
            'BitvoUserAgent',
            'Bizbot003',
            'BizBot04 kirk.overleaf.com',
            'BizWorks Retriever',
            'Black Hole',
            'Black.Hole',
            'Blackbird',
            'BlackMask.Net Search Engine',
            'BlackWidow',
            'bladder fusion',
            'Blaiz-Bee',
            'BLEXBot',
            'Blinkx/DFS-Fetch',
            'BlitzBOT',
            'Blog Conversation Project',
            'BlogMyWay',
            'BlogPulseLive',
            'BlogRefsBot',
            'BlogScope',
            'Blogslive',
            'BloobyBot',
            'BlowFish',
            'BLT',
            'bnf.fr_bot',
            'BoaConstrictor',
            'BoardReader-Image-Fetcher',
            'BOI_crawl_00',
            'BOIA-Scan-Agent',
            'BOIA.ORG-Scan-Agent',
            'boitho.com-dc',
            'Bookmark Buddy bookmark checker',
            'Bookmark search tool',
            'bosug',
            'Bot Apoena',
            'Bot',
            'bot',
            'BOT',
            'BotALot',
            'BotRightHere',
            'Botswana',
            'bottybot',
            'BpBot',
            'BRAINTIME_SEARCH',
            'BrokenLinkCheck.com',
            'BrowserEmulator',
            'BrowserMob',
            'BruinBot',
            'BSearchR&D',
            'BSpider',
            'btbot',
            'Btsearch',
            'Buddy',
            'Buibui',
            'BuildCMS crawler',
            'BuiltBotTough',
            'Bullseye',
            'bumblebee',
            'BunnySlippers',
            'BuscadorClarin',
            'Buscaplus Robi',
            'Butterfly',
            'BuyHawaiiBot',
            'BuzzBot',
            'byindia',
            'BYINDIA',
            'BySpider',
            'byteserver',
            'bzBot',
            'c r a w l 3 r',
            'CacheBlaster',
            'Caddbot',
            'Cafi',
            'Camcrawler',
            'CamelStampede',
            'Canon-WebRecord',
            'Canon-WebRecordPro',
            'CareerBot',
            'cataguru',
            'CatchBot',
            'CazoodleBot',
            'CCBot',
            'CCGCrawl',
            'ccubee',
            'CD-Preload',
            'CE-Preload',
            'Cegbfeieh',
            'Cerberian Drtrs',
            'CERT FigleafBot',
            'cfetch',
            'CFNetwork',
            'Chameleon',
            'Charlotte',
            'Check&Get',
            'Checkbot',
            'CheckLinks',
            'Checklinks',
            'CheeseBot',
            'ChemieDE-NodeBot',
            'CherryPicker',
            'CherryPickerElite',
            'CherryPickerSE',
            'Chilkat',
            'ChinaClaw',
            'CipinetBot',
            'cis455crawler',
            'citeseerxbot',
            'cizilla.com/Cizilla-',
            'ClariaBot',
            'Climate Ark',
            'ClimateArk Spider',
            'Clushbot',
            'COAST scan engine',
            'COAST WebMaster Pro',
            'coccoc',
            'CollapsarWEB',
            'Collector',
            'Combine',
            'combine',
            'COMBINE',
            'Compatible',
            'ConnectSearch',
            'conpilot',
            'ContentSmartz',
            'ContextAd Bot',
            'contype',
            'cookieNET',
            'CoolBot ',
            'CoolCheck',
            'Copernic',
            'Copier',
            'CopyRightCheck',
            'core-project',
            'cosmos',
            'Covario-IDS',
            'Cowbot-',
            'Cowdog Bot',
            'crabbyBot',
            'Crawl_Application',
            'crawl.UserAgent',
            'Crawl',
            'crawl',
            'CrawlConvera',
            'Crawler',
            'crawler',
            'crawler_for_infomine',
            'CRAWLER-ALTSE.VUNET.ORG-Lynx',
            'crawler-upgrade-config',
            'crawler.kpricorn.org',
            'crawler@',
            'crawler43.ejupiter.com',
            'crawler4j',
            'Crawly',
            'CreativeCommons',
            'Crescent',
            'Crescent Internet ToolPak HTTP OLE Control v.1.0',
            'cs-crawler',
            'CSE HTML Validator',
            'CSHttpClient',
            'Cuasarbot',
            'culsearch/culs',
            'Curl',
            'Custo',
            'cvaulev',
            'Cyberdog',
            'CyberNavi_WebGet',
            'CyberPatrol SiteCat Webbot',
            'CyberSpyder',
            'CydralSpider',
            'D1GArabicEngine',
            'DA',
            'DataCha0s',
            'DataFountains',
            'DataFountains/DMOZ Downloader',
            'DataparkSearch',
            'datascape robot',
            'DataSpearSpiderBot',
            'DataSpider',
            'Dattatec.com',
            'Dattatec.com-Sitios-Top',
            'Daumoa',
            'DAUMOA-video',
            'DAUMOA-web',
            'Declumbot',
            'Deepindex',
            'deepnet crawler',
            'DeepTrawl',
            'dejan',
            'del.icio.us-thumbnails',
            'DelvuBot',
            'Der große BilderSauger',
            'DiaGem',
            'Diamond',
            'DiamondBot',
            'DiBot',
            'didaxusbot',
            'DigExt',
            'Digger',
            'DiGi-RSSBot',
            'DigitalArchivesBot',
            'DigOut4U',
            'DIIbot',
            'Dillo',
            'Dir_Snatch.exe',
            'DISCo',
            'DISCo Pump',
            'DISCo Pump 3.0',
            'DISCo Pump 3.2',
            'DISCoFinder',
            'Distilled-Reputation-Monitor',
            'Dit',
            'DittoSpyder',
            'DjangoTraineeBot',
            'DKIMRepBot',
            'DoCoMo',
            'DOF-Verify',
            'Domaincrawler',
            'domaincrawler',
            'DomainScan',
            'DomainWatcher Bot',
            'DotBot',
            'DotBot/1.1',
            'DotSpotsBot',
            'Dow Jones Searchbot',
            'Download',
            'Download Demon',
            'Download Demon/3.2.0.8',
            'Download Demon/3.5.0.11',
            'Download Devil',
            'Download Master',
            'Download Ninja',
            'Download Wonder',
            'Downloader',
            'DOY',
            'dragonfly',
            'Drip',
            'drone',
            'Drupal',
            'DTAAgent',
            'dtSearchSpider',
            'dumbot',
            'Dumbot',
            'Dwaar',
            'Dwaarbot',
            'DXSeeker',
            'EAH',
            'Earth Platform Indexer',
            'Earth Science Educator  robot',
            'EARTHCOM.info',
            'EARTHCOM',
            'EasyDL',
            'ebingbong',
            'EC2LinkFinder',
            'eCairn-Grabber',
            'eCatch',
            'eCatch/3.0',
            'eChooseBot',
            'EdisterBot (http://www.edister.com/bot.html)',
            'EduGovSearch',
            'egothor',
            'eidetica . com / spider',
            'EirGrabber',
            'Elblindo the Blind Bot',
            'ElisaBot',
            'EllerdaleBot',
            'EMail Exractor',
            'EmailCollector',
            'EmailLeach',
            'EmailSiphon',
            'EmailWolf',
            'EMPAS_ROBOT',
            'EnaBot',
            'endeca',
            'EnigmaBot',
            'Enswer Neuro Bot',
            'EntityCubeBot',
            'EroCrawler',
            'es',
            'eStyleSearch',
            'eSyndiCat Bot',
            'Eurosoft - Bot',
            'Evaal',
            'Eventware',
            'Everest - Vulcan Inc . ',
            'Exabot',
            'Exabot Test',
            'Exabot - Images',
            'Exabot - Test',
            'Exabot - XXX',
            'ExaBotTest',
            'ExactSearch',
            'exactseek . com',
            'exooba / exooba crawler',
            'Exploder',
            'Express WebPictures',
            'Extractor',
            'ExtractorPro',
            'EyeNetIE',
            'ez - robot',
            'Ezooms',
            'f - bot test pilot',
            'factbot',
            'Factbot',
            'FairAd Client',
            'falcon',
            'Falconsbot',
            'FAST Data Search Document Retriever',
            'FAST ESP',
            'fast - search - engine',
            'fastbot crawler',
            'fastbot . de crawler',
            'FatBot',
            'Favcollector',
            'Faviconizer',
            'Favorites Sweeper',
            'FDM 1.x',
            'FDM 2.x',
            'FDM 3',
            'FDSE robot',
            'FedContractorBot',
            'fembot',
            'Fetch API Request',
            'fetch_ici',
            'fgcrawler',
            'Filangy',
            'FileHound',
            'FindAnISP . com_ISP_Finder',
            'findlinks',
            'FindWeb',
            'Firebat',
            'FirstGov . gov Search',
            'Flaming AttackBot',
            'Flamingo_SearchEngine',
            'FlashCapture',
            'FlashGet',
            'FlashGet WebWasher 3.2',
            'FlickySearchBot',
            'Fluffy the spider',
            'flunky',
            'focused_crawler',
            'FollowSite',
            'Foobot',
            'Fooooo_Web_Video_Crawl',
            'Fopper',
            'Forest Conservation Portal,',
            'Forest Conservation Spider',
            'Forests . org Spider',
            'FormulaFinderBot',
            'Forschungsportal',
            'fr_crawler',
            'Francis',
            'FreeWebMonitoring SiteChecker',
            'FreshDownload',
            'freshlinks . exe',
            'FriendFeedBot',
            'frodo . at',
            'froGgle',
            'FrontPage',
            'FrontPage [NC,OR]',
            'Froola Bot',
            'FU - NBI / FU - NBI - ',
            'full_breadth_crawler',
            'FunnelBack',
            'FurlBot',
            'G10 - Bot',
            'Gaisbot',
            'GaisBot',
            'GalaxyBot',
            'gazz',
            'generate_infomine_category_classifiers',
            'genevabot',
            'genieBot',
            'GenieBotRD_SmallCrawl',
            'Genieo',
            'Geomaxenginebot',
            'geometabot',
            'GeonaBot',
            'GeoVisu',
            'GetHTMLContents',
            'Getleft',
            'GetLeft',
            'GetRight',
            'GetRight / 2.11',
            'GetRight / 3.1',
            'GetRight / 3.2',
            'GetRight / 3.3',
            'GetRight / 3.3.3',
            'GetRight / 3.3.4',
            'GetRight / 4.0.0',
            'GetRight / 4.1.0',
            'GetRight / 4.1.1',
            'GetRight / 4.1.2',
            'GetRight / 4.2',
            'GetRight / 4.2b(Portuguxeas)',
            'GetRight / 4.2c',
            'GetRight / 4.3',
            'GetRight / 4.5',
            'GetRight / 4.5a',
            'GetRight / 4.5b',
            'GetRight / 4.5b1',
            'GetRight / 4.5b2',
            'GetRight / 4.5b3',
            'GetRight / 4.5b6',
            'GetRight / 4.5b7',
            'GetRight / 4.5c',
            'GetRight / 4.5d',
            'GetRight / 4.5e',
            'GetRight / 5.0beta1',
            'GetRight / 5.0beta2',
            'GetSmart',
            'GetURL . rexx v1.05',
            'GetWeb!',
            'Giant',
            'GigablastOpenSource',
            'Gigabot',
            'GigaBot',
            'GigabotSiteSearch',
            'Girafabot',
            'GleameBot',
            'gnome - vfs',
            'Go - Ahead - Got - It',
            'Go!Zilla',
            'GoForIt . com',
            'GOFORITBOT',
            'gold crawler',
            'Goldfire Server',
            'Golem / 1.1',
            'GoodJelly',
            'Gordon - College - Google - Mini',
            'goroam',
            'GoSeebot',
            'gotit',
            'Govbot',
            'GPU p2p crawler',
            'Grabber',
            'GrabNet',
            'Grafula',
            'grapeFX',
            'grapeshot',
            'GrapeshotCrawler / 2.0',
            'grbot',
            'GreenYogi [ZSEBOT]',
            'Gromit',
            'grub',
            'grub crawler',
            'grub - client',
            'Grub',
            'Grubclient - ',
            'GrubNG',
            'GruBot',
            'gsa',
            'gsa - accuracyEval',
            'gsa - crawler',
            'gsa - eusleg',
            'GSLFbot',
            'Gulliver',
            'GulperBot',
            'GurujiBot',
            'GVC BUSINESS crawler',
            'GVC crawler',
            'GVC SEARCH BOT',
            'GVC WEB crawler',
            'GVC Weblink crawler',
            'GVC WORLD LINKS',
            'gvcbot . com',
            'HappyFunBot',
            'Harvest',
            'Harvest / 1.5',
            'HarvestMan',
            'Hatena Antenna',
            'Hawler',
            'hcat',
            'hclsreport - crawler',
            'HD nutch agent',
            'Header_Test_Client',
            'healia / healia',
            'Helix',
            'here will be link to crawler site',
            'heritrix bot',
            'heritrix',
            'Heritrix',
            'heritrix / 3.1.0',
            'heritrix / 3.1.1',
            'hijbul - heritrix - crawler',
            'HiScan',
            'HiSoftware AccMonitor Server',
            'HiSoftware AccVerify',
            'hitcrawler_',
            'hivaBot',
            'hloader',
            'HLoader',
            'HMSEbot',
            'HMView',
            'hoge',
            'holmes',
            'HomePageSearch',
            'Hooblybot - Image',
            'HooWWWer',
            'Hostcrawler',
            'HSFT - Link Scanner',
            'HSFT - LVU Scanner',
            'HSlide',
            'ht://check',
            'htdig',
            'Html Link Validator',
            'HTMLParser',
            'httplib',
            'HTTrack',
            'HTTrack [NC,OR]',
            'HTTrack 3.0',
            'Huaweisymantecspider',
            'hul-wax',
            'humanlinks',
            'HyperEstraier',
            'Hyperix',
            'ia_archiver',
            'IAArchiver-',
            'ibuena',
            'iCab',
            'ICDS-Ingestion',
            'ichiro',
            'iCopyright Conductor',
            'IEAutoDiscovery',
            'IECheck',
            'iHWebChecker',
            'IIITBOT',
            'iim_405',
            'IlseBot',
            'Iltrovatore-Setaccio',
            'IlTrovatore-Setaccio',
            'IlTrovatore',
            'Image Stripper',
            'Image Sucker',
            'ImageBot',
            'imagefortress',
            'ImagesHereImagesThereImagesEverywhere',
            'ImageVisu',
            'imds_monitor',
            'imo-google-robot-intelink',
            'inagist.com url crawler',
            'Industry Cortex Webcrawler',
            'Indy Library',
            'Indy Library [NC,OR]',
            'indylabs_marius',
            'InelaBot',
            'Inet32 Ctrl',
            'inetbot',
            'info seeker',
            'InfoLink',
            'infomine.ucr.edu',
            'INFOMINE',
            'InfoNaviRobot',
            'Informant',
            'Infoseek Sidewinder',
            'InfoSeek Sidewinder',
            'Infoseek SideWinder',
            'InfoTekies',
            'InfoUSABot',
            'INGRID',
            'INGRID/0.1',
            'Inktomi',
            'InsightsCollector',
            'InsightsWorksBot',
            'InspireBot',
            'InsumaScout',
            'Intelix',
            'Intelliseek',
            'InterGET',
            'Internet Ninja',
            'Internet Ninja 4.0',
            'Internet Ninja 5.0',
            'Internet Ninja 6.0',
            'INTERNET RADIO crawler',
            'InternetLinkAgent',
            'Interseek',
            'IOI',
            'ip-web-crawler.com',
            'IPAdd Bot',
            'IpselonBot',
            'Ipselonbot',
            'Iria',
            'IRLbot',
            'Iron33/1.0.2',
            'Isara/Isara-',
            'iSearch',
            'iSiloX',
            'IstellaBot',
            'its-learning crawler',
            'IU_CSCI_B659_class_crawler',
            'iVia Page Fetcher',
            'iVia Site Checker',
            'iVia',
            'JadynAve',
            'JadynAveBot',
            'Jakarta',
            'Jakarta Commons-HttpClient',
            'Jbot',
            'JemmaTheTourist',
            'JennyBot',
            'Jetbot',
            'JetBrains Omea Pro',
            'JetCar',
            'Jim',
            'JoBo',
            'JobSpider_BA',
            'JOC',
            'JOC Web Spider',
            'JoeDog',
            'JoyScapeBot',
            'JSpyda',
            'Junut Bot',
            'JustView',
            'Jyxobot',
            'K.S.Bot',
            'KakcleBot',
            'kalooga',
            'KaloogaBot',
            'KATATUDO-Spider',
            'kbeta1',
            'KeepNI web site monitor',
            'Kenjin.Spider',
            'Keybot Translation-Search-Machine',
            'KeywenBot',
            'Keyword Density/0.9',
            'Keyword.Density',
            'kinjabot',
            'Kitenga-crawler-bot',
            'KiwiStatus',
            'kmbot-',
            'kmccrew Bot Search',
            'Knight',
            'KnowItAll',
            'Knowledge Engine',
            'Knowledge.com',
            'KoepaBot',
            'Koninklijke',
            'KrOWLer',
            'KSbot',
            'kuloko-bot',
            'kulturarw3',
            'KummHttp',
            'Kurzor',
            'Kyluka crawl',
            'L.webis',
            'Labhoo',
            'labourunions411',
            'Lachesis',
            'lachesis',
            'Lament',
            'LamerExterminator',
            'LapozzBot',
            'larbin',
            'LARBIN-EXPERIMENTAL',
            'LBot',
            'LeapTag',
            'LeechFTP',
            'LeechGet',
            'LetsCrawl.com',
            'LexiBot',
            'LexxeBot',
            'lftp',
            'libcrawl',
            'libiViaCore',
            'libWeb/clsHTTP',
            'libwww-perl',
            'likse',
            'Linguee Bot',
            'Link Checker',
            'Link Validator',
            'link_checker',
            'LinkAlarm',
            'linkbot',
            'Linkbot',
            'LinkCheck by Siteimprove.com',
            'LinkCheck Scanner',
            'LinkChecker',
            'linkdex.com',
            'LinkextractorPro',
            'LinkLint',
            'linklooker',
            'Linkman',
            'Links SQL',
            'LinkScan',
            'LinkScan/8.1a.Unix',
            'LinksManager.com_bot',
            'LinkSweeper',
            'LinkWalker',
            'LiteFinder',
            'LitlrBot',
            'Little Grabber at Skanktale.com',
            'Livelapbot',
            'LM Harvester',
            'LMQueueBot',
            'LNSpiderguy',
            'LoadTimeBot',
            'LocalcomBot',
            'locust',
            'LolongBot',
            'LookBot',
            'Lsearch/sondeur',
            'lssbot',
            'LT Scotland Checklink',
            'lwp-request',
            'lwp-trivial',
            'lwp-trivial/1.34',
            'LWP::Simple',
            'LWP/natweb-bad-link-mailer',
            'Lycos_Spider',
            'Lydia Entity Spider',
            'LynnBot',
            'Lytranslate',
            'Mag-Net',
            'Magnet',
            'magpie-crawler',
            'Magus Bot',
            'Mail.Ru_Bot',
            'Mail.RU_Bot',
            'Mail.Ru_Bot/2.0',
            'Mail.Ru',
            'Mail.RU',
            'MAINSEEK_BOT',
            'Mammoth',
            'Map robot',
            'MarkWatch',
            'MaSagool',
            'masidani_bot_',
            'Mass Downloader',
            'Mass Downloader/2.2',
            'Mata Hari',
            'Mata.Hari',
            'matentzn at cs dot man dot ac dot uk',
            'maxamine.com--robot',
            'maxamine.com-robot',
            'maxomobot',
            'McBot',
            'medrabbit',
            'Megite',
            'MemacBot',
            'Memo',
            'MendeleyBot',
            'Mercator-',
            'mercuryboard_user_agent_sql_injection.nasl',
            'metacarta',
            'Metaeuro Web Search',
            'Metager2',
            'metager2-verification-bot',
            'MetaGloss',
            'metal crawler',
            'metaquerier.cs.uiuc.edu',
            'METASpider',
            'Metaspinner',
            'MetaURI API/2.0  metauri.com',
            'MetaURI API/2.0 +metauri.com',
            'MFcrawler',
            'MFHttpScan',
            'MIDown tool',
            'MIIxpc',
            'MIIxpc/4.2',
            'mini-robot',
            'minibot',
            'miniRank',
            'Mirror',
            'Missigua Locator',
            'Mister PiX',
            'Mister Pix II 2.01',
            'Mister Pix II 2.02a',
            'Mister PiX version.dll',
            'Mister.PiX',
            'Miva',
            'MJ12bot',
            'mnoGoSearch',
            'MnoGoSearch',
            'mod_accessibility',
            'moduna.com',
            'moget',
            'moget/2.1',
            'MojeekBot',
            'MonkeyCrawl',
            'MOSES',
            'mowserbot',
            'MQbot',
            'MSE360',
            'MSIndianWebcrawl',
            'MSMOBOT',
            'msnbot-products',
            'MSNPTC',
            'MSRBOT',
            'MT-Soft',
            'MultiText',
            'My_Little_SearchEngine_Project',
            'my-heritrix-crawler',
            'MyApp',
            'MYCOMPANYBOT',
            'mycrawler',
            'MyEngines-US-Bot',
            'MyFamilyBot',
            'Myra',
            'nabot',
            'nabot_',
            'Najdi.si',
            'Nambu',
            'NAMEPROTECT',
            'NASA Search',
            'NatchCVS',
            'National Park Service Dan Buan',
            'naver',
            'naverbookmarkcrawler',
            'NaverBot_dloader',
            'NaverBot-',
            'NaverBot',
            'Navroad',
            'NearSite',
            'NEC-MeshExplorer',
            'NeoScioCrawler',
            'NerdByNature.Bot',
            'NerdyBot',
            'Nerima-crawl-',
            'Nessus',
            'NESSUS::SOAP',
            'nestReader',
            'Net Vampire',
            'Net Vampire/3.0',
            'Net::Trackback',
            'NetAnts',
            'NetAnts/1.10',
            'NetAnts/1.23',
            'NetAnts/1.24',
            'NetAnts/1.25',
            'NetCarta CyberPilot Pro',
            'Netcraft',
            'NetID.com Bot',
            'NetMechanic',
            'Netprospector',
            'NetResearchServer',
            'NetSeer',
            'NetSeer crawler',
            'NetSeer crawler/2.0',
            'NetShift=',
            'NetSongBot',
            'Netsparker',
            'NetSpider',
            'NetSrcherP',
            'NetZIP',
            'NewMedhunt',
            'news bot ',
            'News_Search_App',
            'NewsGatherer',
            'Newsgroupreporter',
            'NewsTroveBot',
            'NextGenSearchBot',
            'nextthing.org',
            'NG',
            'nicebot',
            'NICErsPRO',
            'niki-bot',
            'NimbleCrawler',
            'nimbus-1',
            'ninetowns',
            'Ninja',
            'NjuiceBot',
            'NLese',
            'NLESE USEPA',
            'Nogate',
            'Norbert the Spider',
            'NoteworthyBot',
            'NPbot',
            'NPBot',
            'NPBot-',
            'NRCan intranet crawler',
            'NSDL_Search_Bot',
            'nu_tch-princeton/Nu_tch',
            'nuggetize.com BOT',
            'nuSearch Spider',
            'NuSearch Spider',
            'Nusearch Spider',
            'Nutch',
            'nutch',
            'nutch1/huntsman',
            'NutchCVS',
            'NutchOrg',
            'NWSpider',
            'Nymesis',
            'nys-crawler',
            'ObjectsSearch',
            'oBot',
            'Obvius external linkcheck',
            'Ocelli',
            'Octopus',
            'ODP entries t_st',
            'oegp v.',
            'Offline Explorer',
            'Offline Explorer/1.2',
            'Offline Explorer/1.4',
            'Offline Explorer/1.6',
            'Offline Explorer/1.7',
            'Offline Explorer/1.9',
            'Offline Explorer/2.0',
            'Offline Explorer/2.1',
            'Offline Explorer/2.3',
            'Offline Explorer/2.4',
            'Offline Explorer/2.5',
            'Offline Navigator',
            'Offline.Explorer',
            'OGspider',
            'OmiExplorer_Bot',
            'OmniExplorer_Bot',
            'OmniFind',
            'omnifind',
            'OmniWeb',
            'OnetSzukaj',
            'online link validator',
            'OOZBOT',
            'Openbot',
            'Openfind',
            'Openfind data gatherer',
            'OpenIntelligenceData',
            'OpenISearch',
            'OpenLink Virtuoso RDF crawler',
            'OpenSearchServer_Bot',
            'OpiDig',
            'optidiscover',
            'Oracle Secure Enterprise Search',
            'Oracle Ultra Search',
            'OrangeBot',
            'ORISBot',
            'ornl_crawler_1',
            'ORNL_Mercury',
            'osis-project.jp',
            'OsO',
            'OutfoxBot',
            'OutfoxMelonBot',
            'OWLER-BOT',
            'owsBot',
            'ozelot',
            'P3P Client',
            'page_verifier',
            'PageBitesHyperBot',
            'Pagebull',
            'PageDown',
            'PageFetcher',
            'PageGrabber',
            'PagePeeker',
            'PageRank Monitor',
            'pamsnbot.htm',
            'Panopy Bot',
            'panscient.com',
            'Pansophica',
            'Papa Foto',
            'PaperLiBot',
            'PaperLiBot/2.1',
            'parasite',
            'parsijoo',
            'Pathtraq',
            'Pattern',
            'Patwebbot',
            'pavuk',
            'PaxleFramework',
            'PBBOT',
            'pcBrowser',
            'pd-crawler',
            'penthesila',
            'perform_crawl',
            'PerMan',
            'PerMan Surfer',
            'personal ultimate crawler',
            'PHP version tracker',
            'PHPCrawl',
            'PhpDig',
            'PicoSearch',
            'PIENO robot',
            'pipBot',
            'pipeLiner',
            'Pita',
            'pixfinder',
            'PiyushBot',
            'plaNETWORK Bot Search',
            'Plucker',
            'Plukkie',
            'Plumtree 6.0',
            'Pockey',
            'Pockey-GetHTML',
            'PoCoHTTP',
            'pogodak.ba',
            'Pogodak.co.yu',
            'Poirot',
            'polybot',
            'Pompos',
            'Poodle predictor',
            'PopScreenBot',
            'PostPost',
            'PrivacyFinder',
            'ProjectWF-java-test-crawler',
            'ProPowerBot/2.14',
            'ProWebWalker',
            'Proxem WebSearch',
            'proximic',
            'PROXY crawler',
            'psbot',
            'PsBot',
            'psbot-page',
            'PSS-Bot',
            'psycheclone',
            'pub-crawler',
            'pucl',
            'pulseBot (pulse Web Miner)',
            'Pump',
            'PWeBot',
            'Python-urllib',
            'pythonic-crawler',
            'PythonWikipediaBot',
            'q1',
            'QEAVis agent',
            'QFKBot',
            'qualidade',
            'Qualidator.com Bot',
            'QuepasaCreep',
            'QueryN Metasearch',
            'QueryN.Metasearch',
            'quest.durato',
            'Quintura-Crw',
            'QunarBot',
            'Qweery_robot.txt_CheckBot',
            'QweeryBot',
            'r2iBot',
            'R6_CommentReader',
            'R6_FeedFetcher',
            'R6_VoteReader',
            'RaBot',
            'Radian6',
            'radian6_linkcheck',
            'Radiation Retriever 1.1',
            'RAMPyBot',
            'RankurBot/Rankur',
            'Rational SiteCheck',
            'RcStartBot',
            'RealDownload',
            'RealDownload/4.0.0.40',
            'RealDownload/4.0.0.41',
            'RealDownload/4.0.0.42',
            'Reaper',
            'REBI-Shoveler',
            'REBI-shoveler',
            'Recorder',
            'RedBot',
            'RedCarpet',
            'ReGet',
            'RepoMonkey',
            'RepoMonkey Bait & Tackle/v1.01',
            'research robot',
            'Riddler',
            'RIIGHTBOT/RIIGHT-',
            'RiseNetBot',
            'RiverGlassScanner',
            'RiverglassScanner',
            'RMA',
            'RoboPal',
            'Robosourcer',
            'Robot',
            'ROBOT',
            'robot',
            'robotek',
            'robots',
            'Robozilla',
            'rogerBot',
            'Rome Client',
            'Rondello',
            'Rotondo',
            'Roverbot',
            'RPT-HTTPClient',
            'rtgibot',
            'RufusBot',
            'Runnk online rss reader',
            'Runnk RSS aggregator',
            's~stremor-crawler',
            'S2Bot',
            'SafariBookmarkChecker',
            'SafetyNet Robot 0.1',
            'SaladSpoon/ShopSalad',
            'Sapienti/Indexer',
            'SBIder',
            'SBL-BOT',
            'SCFCrawler/Nutch-1.8',
            'Scich',
            'ScientificCommons.org',
            'ScollSpider',
            'ScooperBot',
            'Scooter',
            'ScoutJet',
            'ScrapeBox',
            'Scrapy',
            'SCrawlTest',
            'Scrubby',
            'scSpider',
            'Scumbot',
            'Search Publisher',
            'search x-bot',
            'Search-Channel',
            'Search-Engine-Studio',
            'search.KumKie.com',
            'search.msn.com/msnbot.htm',
            'search.updated.com',
            'search.usgs.gov',
            'Searcharoo.NET',
            'SearchBlox',
            'searchbot',
            'SearchBot',
            'searchengine',
            'searchhippo.com',
            'SearchIt-Bot',
            'searchmarking',
            'searchmarks',
            'searchmee_v',
            'Searchmee! Spider',
            'searchmining',
            'SearchnowBot_v1',
            'searchpreview',
            'SearchSpider.com',
            'SearQuBot/SearQuBot v1.0',
            'SEB Spider',
            'Seekbot',
            'Seeker.lookseek.com',
            'SeeqBot',
            'seeqpod-vertical-crawler',
            'Selflinkchecker',
            'Semager',
            'semanticdiscovery',
            'Semantifire1',
            'semisearch',
            'SemrushBot',
            'SEOENGWorldBot',
            'SeznamBot',
            'SeznamBot/2.0',
            'SeznamBot/3.2-test1',
            'ShablastBot',
            'ShadowWebAnalyzer',
            'Shareaza',
            'Shelob',
            'sherlock',
            'ShopWiki',
            'ShowLinks',
            'ShowyouBot',
            'siclab',
            'silk',
            'Siphon',
            'SiteArchive',
            'SiteCheck-sitecrawl by Siteimprove.com',
            'sitecheck.internetseer.com',
            'SiteFinder',
            'SiteGuardBot',
            'SiteOrbiter',
            'SiteSnagger',
            'SiteSucker',
            'SiteSweeper',
            'SiteXpert',
            'SkimBot',
            'SkimWordsBot',
            'SkreemRBot',
            'Skywalker',
            'Sleipnir',
            'slow-crawler',
            'SlySearch',
            'smart-crawler',
            'SmartDownload',
            'SmartDownload/1.2.76 (Win32; Apr 1 1999)',
            'SmartDownload/1.2.77 (Win32; Aug 17 1999)',
            'SmartDownload/1.2.77 (Win32; Feb 1 2000)',
            'SmartDownload/1.2.77 (Win32; Jun 19 2001)',
            'Smarte Bot',
            'smartwit.com',
            'Snake',
            'snap.com beta crawler',
            'Snapbot',
            'SnapPreviewBot',
            'Snappy',
            'snookit/Snookit',
            'Snooper/b97_01',
            'Snoopy',
            'SocSciBot',
            'SOFT411 Directory',
            'sogou',
            'Sogou',
            'sohu agent',
            'sohu-search',
            'Sokitomi crawl',
            'Solbot/1.0 LWP/5.07',
            'sootle',
            'Sosospider',
            'Space Bison',
            'Space Fung',
            'SpaceBison',
            'SpankBot',
            'spanner',
            'Spanner/1.0 (Linux 2.0.27 i586)',
            'Spatineo Monitor Controller',
            'Spatineo Serval Controller',
            'Spatineo Serval GetMapBot',
            'special_archiver',
            'Speedy Spider',
            'SpeedySpider',
            'Sphere Scout',
            'Sphere Scout&v',
            'Sphider',
            'Sphider2',
            'spider',
            'Spider',
            'Spider.TerraNautic.net',
            'SpiderEngine',
            'SpiderKU',
            'SpiderMan',
            'Spinn3r',
            'Spinne',
            'sportcrew-Bot',
            'spyder3.microsys.com',
            'SQ Webscanner',
            'sqlmap',
            'Squid-Prefetch',
            'SquidClamAV_Redirector',
            'Sqworm',
            'SrevBot',
            'sslbot',
            'SSM Agent',
            'StackRambler',
            'StarDownloader',
            'statbot',
            'statcrawler',
            'statedept-crawler',
            'Steeler',
            'STEGMANN-Bot',
            'stero',
            'Stripper',
            'Stumbler',
            'suchclip',
            'Sucker',
            'SumeetBot',
            'SumitBot',
            'SummizeBot',
            'SummizeFeedReader',
            'Sunrise XP',
            'SuperBot',
            'superbot.com',
            'SuperBot/3.0 (Win32)',
            'SuperBot/3.1 (Win32)',
            'SuperHTTP',
            'SuperLumin Downloader',
            'SuperPagesBot',
            'Supybot',
            'SURF',
            'Surfbot',
            'SurfControl',
            'SurveyBot',
            'suzuran',
            'SWEBot',
            'swish-e',
            'SygolBot',
            'SynapticWalker',
            'Syntryx ANT Scout Chassis Pheromone',
            'SystemSearch-robot',
            'Szukacz',
            'Szukacz/1.4',
            'T-H-U-N-D-E-R-S-T-O-N-E',
            'Tailrank',
            'tAkeOut',
            'Talkro Web-Shot',
            'TAMU_CRAWLER',
            'TapuzBot',
            'Tarantula',
            'targetblaster.com',
            'TargetYourNews.com bot',
            'TAUSDataBot',
            'taxinomiabot',
            'TeamSoft WinInet Component',
            'Tecomi Bot',
            'TeezirBot',
            'Teleport',
            'Teleport Pro',
            'Teleport Pro/1.29',
            'Teleport Pro/1.29.1590',
            'Teleport Pro/1.29.1634',
            'Teleport Pro/1.29.1718',
            'Teleport Pro/1.29.1820',
            'Teleport Pro/1.29.1847',
            'TeleportPro',
            'Telesoft',
            'Teradex Mapper',
            'TERAGRAM_CRAWLER',
            'TerrawizBot',
            'TestBot',
            'testbot',
            'testBOT',
            'testing of bot',
            'TextBot',
            'thatrobotsite.com',
            'The Dyslexalizer',
            'The Intraformant',
            'The.Intraformant',
            'TheNomad',
            'Theophrastus',
            'theusefulbot',
            'TheUsefulbot_',
            'ThumbBot',
            'Thumbnail.CZ robot',
            'thumbshots-de-bot',
            'tigerbot',
            'TightTwatBot',
            'TinEye',
            'Titan',
            'TITAN',
            'to-dress_ru_bot_',
            'to-night-Bot',
            'toCrawl/UrlDispatcher',
            'Topicalizer',
            'topicblogs',
            'Toplistbot',
            'TopServer PHP',
            'topyx-crawler',
            'Touche',
            'TourlentaScanner',
            'TPSystem',
            'TRAAZI',
            'TranSGeniKBot',
            'travel-search',
            'TravelBot',
            'TravelLazerBot',
            'Treezy',
            'TREX',
            'TridentSpider',
            'Trovator',
            'True_Robot',
            'tScholarsBot',
            'TSM Translation-Search-Machine',
            'TsWebBot',
            'TulipChain',
            'turingos',
            'TurnitinBot',
            'TurnitinBot/1.5',
            'TutorGigBot',
            'TweetedTimes Bot',
            'TweetmemeBot',
            'TwengaBot',
            'TwengaBot-Discover',
            'Twiceler',
            'Twikle',
            'twinuffbot',
            'Twisted PageGetter',
            'Twitturls',
            'Twitturly ',
            'TygoBot',
            'TygoProwler',
            'Typhoeus',
            'U.S. Government Printing Office',
            'uberbot',
            'ucb-nutch',
            'UdmSearch',
            'UFAM-crawler-',
            'Ultraseek',
            'UnChaos',
            'unchaos_crawler_',
            'UnisterBot',
            'Unitek UniEngine',
            'UniversalSearch',
            'UnwindFetchor',
            'UofTDB_experiment',
            'updated',
            'URL Control',
            'url_gather',
            'URL-Checker',
            'URLAppendBot',
            'URLBlaze',
            'urlchecker',
            'urlck/1.2.3',
            'UrlDispatcher',
            'URLSpiderPro',
            'URLy Warning',
            'URLy.Warning',
            'USAF AFKN K2SPIDER',
            'usasearch',
            'USS-Cosmix',
            'USyd-NLP-Spider',
            'Vacobot',
            'Vacuum',
            'VadixBot',
            'Vagabondo',
            'Validator',
            'Valkyrie/1.0 libwww-perl/0.40',
            'vBSEO',
            'VCI',
            'VCI WebViewer VCI WebViewer Win32',
            'VerbstarBot',
            'VeriCiteCrawler/Nutch-2.2.1',
            'Verifactrola',
            'Verity-URL-Gateway',
            'Vermut',
            'vermut',
            'versus crawler',
            'versus.integis.ch',
            'viasarchivinginformation.html',
            'VIP',
            'VIPr',
            'virus_detector',
            'virus-detector',
            'VisBot',
            'Vishal For CLIA',
            'VisWeb',
            'Vital Search n Urchin',
            'vlad',
            'vlsearch',
            'VMBot',
            'VocusBot',
            'VoidEYE',
            'VoilaBot',
            'Vortex',
            'voyager-hc',
            'voyager-partner-deep',
            'voyager',
            'VSE',
            'vspider',
            'W3C_Unicorn',
            'W3C-WebCon',
            'w3m',
            'w3search',
            'wacbot',
            'wastrix',
            'Water Conserve Portal',
            'Water Conserve Spider',
            'WatzBot',
            'wauuu engine/Wauuu',
            'Wavefire',
            'Waypath',
            'Wazzup',
            'Wazzup1.0.4800',
            'wbdbot',
            'Web CEO Online robot',
            'web crawler',
            'Web Downloader',
            'Web Image Collector',
            'Web Link Validator',
            'Web Magnet',
            'Web Site Downloader',
            'Web Sucker',
            'web-agent',
            'Web-Sniffer',
            'Web.Image.Collector',
            'WebaltBot',
            'WebAuto',
            'WebAuto/3.40',
            'WebBandit',
            'webbandit',
            'WebBandit/3.50',
            'WebBOT',
            'webbot',
            'WebBot',
            'webbul-bot',
            'WebCapture',
            'WebCapture 2.0',
            'webcheck 1',
            'Webclipping.com',
            'webcollage',
            'WebCopier',
            'WebCopier v.2.2',
            'WebCopier v2.5',
            'WebCopier v2.6',
            'WebCopier v2.7a',
            'WebCopier v2.8',
            'WebCopier v3.0',
            'WebCopier v3.0.1',
            'WebCopier v3.2',
            'WebCopier v3.2a',
            'WebCopy',
            'WebCorp',
            'webcrawl.net',
            'WebCrawler',
            'webcrawler',
            'WebCrawler/3.0 Robot libwww/5.0a',
            'WebDownloader for X',
            'Webdup',
            'WebEMailExtrac',
            'WebEnhancer',
            'WebFetch',
            'webfetch',
            'WebFetcher/0.8,',
            'WebGather',
            'WebGo IS',
            'webGobbler',
            'WebImages',
            'Webinator-search2.fasthealth.com',
            'Webinator-WBI',
            'WebIndex',
            'WebIndexer',
            'weblayers/0.0',
            'WebLeacher',
            'WeblexBot',
            'WebLinker/0.0 libwww-perl/0.1',
            'webLyzard',
            'WebmasterCoffee',
            'WebmasterWorld Extractor',
            'WebmasterWorldForumBot',
            'WebMiner',
            'WebMoose/0.0.0000',
            'WeBot',
            'WebPix',
            'WebReaper',
            'WebRipper',
            'WebSauger',
            'WebSauger 1.20b',
            'WebSauger 1.20j',
            'WebSauger 1.20k',
            'Webscan',
            'websearchbench',
            'WebSite',
            'Website Downloader',
            'Website Explorer',
            'Website eXtractor',
            'Website Quester',
            'Website.Quester',
            'websitemirror',
            'WebSpear',
            'websphinx.test',
            'WebSpider',
            'Webster',
            'Webster Pro',
            'Webster.Pro',
            'WebStripper',
            'WebStripper/2.03',
            'WebStripper/2.10',
            'WebStripper/2.12',
            'WebStripper/2.13',
            'WebStripper/2.15',
            'WebStripper/2.16',
            'WebStripper/2.19',
            'WebTrafficExpress',
            'WebTrends Link Analyzer',
            'WebVac',
            'webwalk',
            'WebWalker',
            'WebWalker/1.10',
            'WebWasher',
            'Webwasher',
            'WebWatch',
            'WebWhacker',
            'WebXM',
            'WebZIP',
            'Weddings.info Bot',
            'wenbin/search',
            'WEP Search',
            'WEPA',
            'WeRelateBot',
            'Wget',
            'wget',
            'Wget/1.4.0',
            'Wget/1.5.2',
            'Wget/1.5.3',
            'Wget/1.6',
            'Wget/1.7',
            'Wget/1.8',
            'Wget/1.8.1',
            'Wget/1.8.1+cvs',
            'Wget/1.8.2',
            'Wget/1.9-beta',
            'Whacker',
            'Whirlpool Web Engine',
            'WhoWhere Robot',
            'Widow',
            'WikiaBot',
            'Wikio',
            'wikiwix-bot-',
            'WinHTTP Example',
            'WinHttp.WinHttpRequest.',
            'WIRE',
            'wired-digital-newsbot/1.5',
            'WISEbot',
            'WISENutbot',
            'wish-la',
            'wish-project',
            'wisponbot',
            'WMCAI-robot',
            'wminer',
            'WMSBot',
            'woriobot',
            'worldshop',
            'WorQmada',
            'Wotbox',
            'wume_crawler',
            'WWW Collector',
            'WWW-Collector-E',
            'WWW-Mechanize',
            'WWWOFFLE',
            'wwwrobot',
            'wwwster',
            'WWWWanderer v3.0',
            'wwwxref',
            'Wysigot',
            'X-clawler',
            'X-crawler',
            'Xaldon',
            'Xaldon WebSpider',
            'Xaldon WebSpider 2.5.b3',
            'Xaldon_WebSpider',
            'Xenu',
            'Xenu',
            'Xenu Link Sleuth 1.1c',
            'Xerka MetaBot',
            'Xerka WebBot',
            'XGET/0.7',
            'xirq',
            'XmarksFetch',
            'xqrobot',
            'Y!J-BRI',
            'Y!J-BRJ/YATS crawler',
            'Y!J-BRW',
            'Y!J-BSC',
            'Y!J-PSC',
            'Y!J-SRD',
            'Y!J',
            'Y!TunnelPro',
            'yacy.net',
            'yacybot',
            'Yandex',
            'YandexBot',
            'YandexSomething',
            'Yanga WorldSearch Bot',
            'yarienavoir.net',
            'Yasaklibot',
            'yBot',
            'YebolBot',
            'yellowJacket',
            'yes',
            'YesupBot',
            'Yeti',
            'YioopBot',
            'yolinkBot',
            'yoogliFetchAgent',
            'Yoono',
            'yoono',
            'Yoriwa',
            'YottaCars_Bot',
            'you-dir',
            'Z-Add Link Checker',
            'zagrebin',
            'Zao',
            'zedzo.digest',
            'zedzo.validate',
            'zermelo',
            'Zeus',
            'Zeus 11389 Webster Pro V2.9 Win32',
            'Zeus 11652 Webster Pro V2.9 Win32',
            'Zeus 18018 Webster Pro V2.9 Win32',
            'Zeus 26378 Webster Pro V2.9 Win32',
            'Zeus 30747 Webster Pro V2.9 Win32',
            'Zeus 32297 Webster Pro V2.9 Win32',
            'Zeus 39206 Webster Pro V2.9 Win32',
            'Zeus 41641 Webster Pro V2.9 Win32',
            'Zeus 44238 Webster Pro V2.9 Win32',
            'Zeus 51070 Webster Pro V2.9 Win32',
            'Zeus 51674 Webster Pro V2.9 Win32',
            'Zeus 51837 Webster Pro V2.9 Win32',
            'Zeus 63567 Webster Pro V2.9 Win32',
            'Zeus 6694 Webster Pro V2.9 Win32',
            'Zeus 82016 Webster Pro V2.9 Win32',
            'Zeus 82900 Webster Pro V2.9 Win32',
            'Zeus 84842 Webster Pro V2.9 Win32',
            'Zeus 90872 Webster Pro V2.9 Win32',
            'Zeus 94934 Webster Pro V2.9 Win32',
            'Zeus 95245 Webster Pro V2.9 Win32',
            'Zeus 95351 Webster Pro V2.9 Win32',
            'Zeus 97371 Webster Pro V2.9 Win32',
            'Zeus Link Scout',
            'zibber-v',
            'zimeno',
            'Zing-BottaBot',
            'ZipppBot',
            'ZoomSpider',
            'Zotag Search',
            'ZuiBot',
            'ZumBot',
            'ZyborẸ̀g',
            'Zyte'
        ];

        // Check if the user agent is in the list of disallowed bots.
        if (in_array($userAgent, $disallowedBots)) {
            return true;
        }

        return false;
    }
}
